variables:

  TAG: "${CI_PIPELINE_IID}"
  IMAGE_NAME: "Test-image"
  CONTAINER_NAME: "Test"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:"$TAG" .
  tags:
    - runner-tag #That Created
  only:
    - deployment-dev #Bracnch Name

deploy:
  stage: deploy
  script:
    - docker rm -f $IMAGE_NAME
    - docker run -d --name $CONTAINER_NAME -p 3000:3000 --restart always $IMAGE_NAME:"$TAG"
  tags:
    - runner-tag #That Created
  only:
    - deployment-dev #Bracnch Name